### ISSUE TITLE
clarify external object requirements 

### ISSUE THREAD

**Issue by bencoman** [SquareBracketAssociates/PharoInProgress#28]
I read...
Any class in the system can be an external object as long as:
• it inherits from FFIExternalObject
• it implements in its class side the method asExternalTypeOn:

which I naturally interpret as an "and" proposition, 
but none of the subclasses of FFIExternalObject define asExternalTypeOn:
and none that define it inherit from FFIExternalObject. 

So I think it must mean...

Any class in the system can be an external object as long as either:
• it inherits from FFIExternalObject; or
• it implements in its class side the method asExternalTypeOn:

**Comment by estebanlm** [comment]
yes, that's correct :)

**Comment by estebanlm** [comment]
are you going to send a PR ? (I see a branch you opened)
